name: Docker Image CI
on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - "web-app-docker/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - "web-app-docker/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file web-app-docker/Dockerfile --tag zeeshanib/webapp-docker:v1
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/webapp-docker:v1
