name: Dispatch
on:
  repository_dispatch:
    types: [run-build-reusable]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch event
      uses: ./.github/workflows/build-reusable.yml

    
